version: '3'

services:

  nginx:
      image: linuxserver/letsencrypt
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./nginx/config:/config
        - ./nginx/nginx.conf:/config/nginx/site-confs/default
        - ./nginx/ssl.conf:/config/nginx/ssl.conf
      container_name: nginx
      restart: unless-stopped
      environment: 
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - URL=colorsfocus.com
        - SUBDOMAINS=www,
        - VALIDATION=http
        - STAGING=false #optional